<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    /**
     * Tables that should be skipped during seeding (system/cache tables).
     */
    protected array $skipTables = [
        'CacheLocksTableSeeder',
        'CacheTableSeeder',
        'SessionsTableSeeder',
        'FailedJobsTableSeeder',
        'JobBatchesTableSeeder',
        'JobsTableSeeder',
        'PasswordResetsTableSeeder',
        'PasswordResetTokensTableSeeder',
    ];

    public function run(): void
    {
        // 1) Auto-run any dump seeders generated by seed:export
        // Skip system tables that may not exist in production
        $dumpDir = database_path('seeders/dumps');
        if (is_dir($dumpDir)) {
            foreach (glob($dumpDir . DIRECTORY_SEPARATOR . '*TableSeeder.php') as $file) {
                $seederName = basename($file, '.php');
                
                // Skip system tables
                if (in_array($seederName, $this->skipTables)) {
                    continue;
                }
                
                require_once $file;
                $class = 'Database\\Seeders\\Dumps\\' . $seederName;
                if (class_exists($class)) {
                    $this->call([$class]);
                }
            }
        }

        // 2) Then run hand-written seeders here
        $this->call([
            SuperAdminSeeder::class,
            AdminUserSeeder::class,
        ]);
    }
}
