<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1) Auto-run any dump seeders generated by seed:export
        // We don't need composer autoload because we will require the file directly
        $dumpDir = database_path('seeders/dumps');
        if (is_dir($dumpDir)) {
            foreach (glob($dumpDir . DIRECTORY_SEPARATOR . '*TableSeeder.php') as $file) {
                require_once $file;
                $class = 'Database\\Seeders\\Dumps\\' . basename($file, '.php');
                if (class_exists($class)) {
                    $this->call([$class]);
                }
            }
        }

        // 2) Then run hand-written seeders here
        $this->call([
            SuperAdminSeeder::class,
        ]);
    }
}
